# WoTLK经典装备中文名称映射
chinese_item_names = {
    # ===== 材料 =====
    "Badge of Justice": "公正徽章",
    "Frozen Orb": "冰冻宝珠",
    "Primordial Saronite": "原始萨隆邪铁",
    "Shadowfrost Shard": "影霜碎片",
    "Fragment of Val'anyr": "瓦兰奈尔碎片",
    "Splinter of Atiesh": "埃提耶什碎片",
    "Frame of Atiesh": "埃提耶什框架",
    "Trophy of the Crusade": "十字军战利品",
    "Champion's Seal": "冠军的徽记",
    "Trance Stone": "恍惚之石",
    "Imperial Qiraji Regalia": "其拉帝王徽记",
    "Imperial Qiraji Armaments": "其拉帝王武器",
    "Qiraji Spiked Hilt": "其拉尖刺剑柄",
    "Qiraji Ornate Hilt": "其拉华丽剑柄",
    "Qiraji Martial Drape": "其拉军用披风",
    "Qiraji Regal Drape": "其拉皇家披风",
    "Qiraji Magisterial Ring": "其拉执政官戒指",
    "Qiraji Ceremonial Ring": "其拉仪式戒指",
    # ===== 宝石袋 =====
    "Yellow Sack of Gems": "黄色宝石袋",
    "Sack of Gems": "宝石袋",
    "Red Sack of Gems": "红色宝石袋",
    "Green Sack of Gems": "绿色宝石袋",
    "Gray Sack of Gems": "灰色宝石袋",
    "Blue Sack of Gems": "蓝色宝石袋",
    # ===== 冬季帽子 =====
    "Red Winter Hat": "红色冬帽",
    "Green Winter Hat": "绿色冬帽",
    # ===== 套装部件模板 =====
    # 失落的征服者系列
    "Spaulders of the Lost Vanquisher": "失落胜利者肩甲",
    "Spaulders of the Lost Protector": "失落守护者肩甲",
    "Spaulders of the Lost Conqueror": "失落征服者肩甲",
    "Leggings of the Lost Vanquisher": "失落胜利者护腿",
    "Leggings of the Lost Protector": "失落守护者护腿",
    "Leggings of the Lost Conqueror": "失落征服者护腿",
    "Helm of the Lost Vanquisher": "失落胜利者头盔",
    "Helm of the Lost Protector": "失落守护者头盔",
    "Helm of the Lost Conqueror": "失落征服者头盔",
    # 迷途的征服者系列
    "Spaulders of the Wayward Vanquisher": "迷途胜利者肩甲",
    "Spaulders of the Wayward Protector": "迷途守护者肩甲",
    "Spaulders of the Wayward Conqueror": "迷途征服者肩甲",
    "Leggings of the Wayward Vanquisher": "迷途胜利者护腿",
    "Leggings of the Wayward Protector": "迷途守护者护腿",
    "Leggings of the Wayward Conqueror": "迷途征服者护腿",
    "Helm of the Wayward Vanquisher": "迷途胜利者头盔",
    "Helm of the Wayward Protector": "迷途守护者头盔",
    "Helm of the Wayward Conqueror": "迷途征服者头盔",
    "Gloves of the Wayward Vanquisher": "迷途胜利者手套",
    "Gloves of the Wayward Protector": "迷途守护者手套",
    "Gloves of the Wayward Conqueror": "迷途征服者手套",
    "Chestguard of the Wayward Vanquisher": "迷途胜利者胸甲",
    "Chestguard of the Wayward Protector": "迷途守护者胸甲",
    "Chestguard of the Wayward Conqueror": "迷途征服者胸甲",
    # 神圣印记系列
    "Vanquisher's Mark of Sanctification": "胜利者的神圣印记",
    "Protector's Mark of Sanctification": "守护者的神圣印记",
    "Conqueror's Mark of Sanctification": "征服者的神圣印记",
    # ===== 经典装备 =====
    "Ahn'kahar Handwraps": "安卡哈护手",
    "Crawler-Emblem Belt": "爬行者徽章腰带",
    "Blade of Nadox": "纳多克斯之刃",
    "Elder Headpiece": "长者头饰",
    "Sprinting Shoulderpads": "疾行肩垫",
    "Brood Plague Helmet": "虫群瘟疫头盔",
    "Nerubian Shield Ring": "蛛魔护盾指环",
    "Staff of the Plague Beast": "瘟疫兽法杖",
    # ===== 旧世经典装备 =====
    "Staff of Rampant Growth": "疯狂生长法杖",
    "Malfurion's Signet Ring": "玛法里奥的徽记之戒",
    "Hammer of Bestial Fury": "野兽之怒锤",
    "Green Dragonskin Cloak": "绿龙鳞披风",
    "Gloves of Delusional Power": "妄想之力手套",
    "Flamewaker Legplates": "烈焰行者腿甲",
    "Dragonspur Wraps": "龙刺裹手",
    "Dragonbone Wristguards": "龙骨护腕",
    "Ancient Corroded Leggings": "远古腐蚀护腿",
    "Acid Inscribed Greaves": "酸蚀护胫",
    "Nightmare Engulfed Object": "梦魇吞噬之物",
    # ===== 附魔公式 =====
    "Formula: Enchant Weapon - Executioner": "公式：附魔武器 - 刽子手",
    # ===== 纳克萨玛斯 =====
    "Kilt of Sewn Flesh": "缝合血肉褶裙",
    "Slaughterhouse Sabatons": "屠宰场战靴",
    "Enchanted Wire Stitching": "附魔钢丝缝线",
    "Meathook's Slicer": "肉钩的切割器",
    "Emblem of Conquest": "征服纹章",
    "Belt of Unified Souls": "灵魂统束腰带",
    "Bile-Cured Gloves": "胆汁浸洗手套",
    "Spaulders of the Abomination": "憎恶肩甲",
    "Legplates of Steel Implants": "钢铁植入护腿",
    "Shoulderpads of the Walking Plague": "瘟疫行者肩垫",
    "Plagueheart Robe": "瘟疫之心长袍",
    "Gloves of the Plaguebringer": "瘟疫使者手套",
    "Plague-Core Belt": "瘟疫核心腰带",
    "Plague Leggings": "瘟疫护腿",
    "Cloak of the Necropolis": "大墓地斗篷",
    "Crown of the Frost Wyrm": "冰霜巨龙之冠",
    "Frost Wyrm Cloak": "冰霜巨龙斗篷",
    "Phylactery of Kel'Thuzad": "克尔苏加德的护符匣",
    "Staff of the Frost Wyrm": "冰霜巨龙法杖",
    "Kel'Thuzad's Reach": "克尔苏加德之握",
    "Frostmourne's Hungry Blade": "霜之哀伤的饥渴之刃",
    "Chestguard of the Frozen Wastes": "冰封废土胸甲",
    "Helm of Domination": "统御头盔",
    "Boots of the Frozen Crypt": "冰封墓穴之靴",
    "Ring of the Archlich": "巫妖王之环",
    "Necklace of the Frozen Wastes": "冰封废土项链",
    "Gauntlets of the Warden": "典狱长护手",
    "Trousers of Eternity": "永恒护腿",
    "Corpse Thread Cloak": "尸体线披风",
    "Grip of the Necropolis": "大墓地之握",
    "Haunted Pauldrons": "闹鬼护肩",
    "Plague Fetid Boots": "恶臭瘟疫之靴",
    "Rune-Etched Blade": "符文蚀刻之刃",
    "Soul-Stealing Cinch": "偷魂束带",
    "Spinebreaker Gauntlets": "断脊护手",
    "Unholy Cloak": "邪恶披风",
    "Vein-Slicer": "切脉者",
    "Virulent Plague Scepter": "剧毒瘟疫节杖",
    "Zombie Skin Leggings": "僵尸皮护腿",
    # ===== 奥杜尔 =====
    "Val'anyr, Hammer of Ancient Kings": "瓦兰奈尔，远古王者之锤",
    "Mimiron's Head": "米米尔隆的头部",
    "Hand of Gul'dan": "古尔丹之手",
    "Saronite Bombs": "萨隆邪铁炸弹",
    "Celestial Plate Helm": "天界板甲头盔",
    "Titansteel Destroyer": "泰坦精钢毁灭者",
    "Fury of the Aspects": "守护巨龙之怒",
    "The Beholder": "魔眼",
    "Eye of Eternity": "永恒之眼",
    "Onyxia Scale Cloak": "奥妮克希亚鳞片披风",
    # ===== 十字军试炼 =====
    "Deathbringer's Will": "死亡使者的意志",
    "Triumphant Legplates": "凯旋护腿",
    "Crusader's Edge": "十字军之刃",
    "Lightsworn Greatsword": "圣光使者巨剑",
    "Valkyr's Kiss": "瓦格里之吻",
    "Frostsilk Robe": "霜丝长袍",
    "Argent Champion's Breastplate": "银色冠军胸甲",
    # ===== 冰冠堡垒 =====
    "Shadowmourne": "影之哀伤",
    "Frostmourne": "霜之哀伤",
    "Helm of the Frost Lord": "霜之领主头盔",
    "Chestguard of the Frozen Throne": "冰封王座胸甲",
    "Leggings of the Scourge": "天灾护腿",
    "Boots of the Apocalypse": "天启之靴",
    "Ring of the Frozen Wastes": "冰封废土之戒",
    "Necklace of the Lich King": "巫妖王项链",
    "Cloak of the Shadow Prince": "暗影王子斗篷",
    "Mace of the Unholy": "邪恶之锤",
    "Blade of the Fallen Prince": "陨落王子之刃",
    "Shield of the Lich King": "巫妖王之盾",
    # ===== 阿尔卡冯的宝库 =====
    "Algalon's Disc": "阿加隆之盘",
    "Emblem of Frost": "冰霜纹章",
    "Titan-Forged Shoulders": "泰坦锻造护肩",
    # ===== 套装 =====
    "Plagueheart Gloves": "瘟疫之心手套",
    "Plagueheart Belt": "瘟疫之心腰带",
    "Plagueheart Leggings": "瘟疫之心护腿",
    "Plagueheart Shoulders": "瘟疫之心护肩",
    "Plagueheart Chest": "瘟疫之心胸甲",
    "Frostfire Robe": "霜火长袍",
    "Frostfire Shoulders": "霜火护肩",
    "Frostfire Chest": "霜火胸甲",
    "Frostfire Leggings": "霜火护腿",
    "Frostfire Gloves": "霜火手套",
    "Frostfire Belt": "霜火腰带",
    "Scourgeborne Plate": "天灾板甲",
    "Scourgeborne Helmet": "天灾头盔",
    "Scourgeborne Shoulders": "天灾护肩",
    "Scourgeborne Chest": "天灾胸甲",
    "Scourgeborne Leggings": "天灾护腿",
    "Scourgeborne Gloves": "天灾手套",
    "Scourgeborne Boots": "天灾之靴",
    "Cryptstalker Armor": "墓穴追踪者护甲",
    "Cryptstalker Helmet": "墓穴追踪者头盔",
    "Cryptstalker Shoulders": "墓穴追踪者护肩",
    "Cryptstalker Chest": "墓穴追踪者胸甲",
    "Cryptstalker Leggings": "墓穴追踪者护腿",
    "Cryptstalker Gloves": "墓穴追踪者手套",
    "Cryptstalker Boots": "墓穴追踪者之靴",
    "Darkruned Armor": "暗纹护甲",
    "Darkruned Helmet": "暗纹头盔",
    "Darkruned Shoulders": "暗纹护肩",
    "Darkruned Chest": "暗纹胸甲",
    "Darkruned Leggings": "暗纹护腿",
    "Darkruned Gloves": "暗纹手套",
    "Darkruned Boots": "暗纹之靴",
    "Ebon Blade Plate": "黑锋板甲",
    "Ebon Blade Helmet": "黑锋头盔",
    "Ebon Blade Shoulders": "黑锋护肩",
    "Ebon Blade Chest": "黑锋胸甲",
    "Ebon Blade Leggings": "黑锋护腿",
    "Ebon Blade Gloves": "黑锋手套",
    "Ebon Blade Boots": "黑锋之靴",
    # ===== 更多装备 =====
    "Emblem of Triumph": "凯旋纹章",
    "Black Ice": "黑冰",
    "Frostmourne's Reach": "霜之哀伤之握",
    "Hailstorm": "冰雹",
    "The Decapitator": "斩首者",
    "The Eye of Observation": "观察之眼",
    "Zul'Drak Slicer": "祖达克切割者",
    "Saronite Razor": "萨隆邪铁剃刀",
    "Titansteel Bonebreaker": "泰坦精钢碎骨锤",
    "Froststeel Longsword": "霜钢长剑",
    "Shadow Edge": "暗影边缘",
    "Death's Verdict": "死亡裁决",
    "Grievous Gladiator's Edge": "残酷角斗士之刃",
    "Wrathful Gladiator's Edge": "狂怒角斗士之刃",
    "Relentless Gladiator's Edge": "无情角斗士之刃",
    "Plagueheart Raiment": "瘟疫之心法衣",
    "Frostfire Regalia": "霜火套装",
    "Scourgeborne Battleplate": "天灾战甲",
    "Cryptstalker Battlegear": "墓穴追踪者战装",
    "Darkruned Battlegear": "暗纹战装",
    "Ebon Blade Battlegear": "黑锋战装",
    "Comet's Trail": "彗星之尾",
    "Mirror of Truth": "真相之镜",
    "Solace of the Fallen": "陨落慰藉",
    "Spark of Hope": "希望火花",
    "Frost Lotus": "冰霜莲花",
    "Tears of the Vanquished": "战败者之泪",
    "Talisman of Resurgence": "复苏护符",
    "Saronite Reaver": "萨隆邪铁掠夺者",
    "Obsidium Slayer": "黑曜石杀手",
    "Frostforged Blade": "霜铸之刃",
    "Frostweave Robe": "霜织长袍",
    "Saronite Plate": "萨隆邪铁板甲",
    "Ebon Plate": "玄铁板甲",
    "Frostscale Armor": "霜鳞护甲",
    "Stormscale Armor": "风暴鳞甲",
    "Voidcloth Robe": "虚空布长袍",
    "Mooncloth Robe": "月布长袍",
    "Nexus-Hopper Boots": "节点跃迁者之靴",
    "Frostscale Breastplate": "霜鳞胸甲",
    "Azure Tides Breastplate": "碧蓝海潮胸甲",
    "Jade-Skull Pauldrons": "碧玉骷髅护肩",
    "Stormcaller's Cloak": "风暴召唤者斗篷",
    "Voidheart Robe": "虚空之心长袍",
    "Warglaive of Azzinoth": "埃辛诺斯战刃",
    "Ashbringer": "灰烬使者",
    "Atiesh, Greatstaff of the Guardian": "埃提耶什，守护者的传说之杖",
    "Thori'dal, the Stars' Fury": "索利达尔，群星之怒",
    # ===== 套装系列 =====
    "Tier 8 Paladin": "T8圣骑士套装",
    "Tier 8 Warrior": "T8战士套装",
    "Tier 8 Hunter": "T8猎人套装",
    "Tier 8 Rogue": "T8潜行者套装",
    "Tier 8 Priest": "T8牧师套装",
    "Tier 8 Shaman": "T8萨满祭司套装",
    "Tier 8 Mage": "T8法师套装",
    "Tier 8 Warlock": "T8术士套装",
    "Tier 8 Death Knight": "T8死亡骑士套装",
    "Tier 8 Druid": "T8德鲁伊套装",
    "Tier 9 Paladin": "T9圣骑士套装",
    "Tier 9 Warrior": "T9战士套装",
    "Tier 9 Hunter": "T9猎人套装",
    "Tier 9 Rogue": "T9潜行者套装",
    "Tier 9 Priest": "T9牧师套装",
    "Tier 9 Shaman": "T9萨满祭司套装",
    "Tier 9 Mage": "T9法师套装",
    "Tier 9 Warlock": "T9术士套装",
    "Tier 9 Death Knight": "T9死亡骑士套装",
    "Tier 9 Druid": "T9德鲁伊套装",
    "Tier 10 Paladin": "T10圣骑士套装",
    "Tier 10 Warrior": "T10战士套装",
    "Tier 10 Hunter": "T10猎人套装",
    "Tier 10 Rogue": "T10潜行者套装",
    "Tier 10 Priest": "T10牧师套装",
    "Tier 10 Shaman": "T10萨满祭司套装",
    "Tier 10 Mage": "T10法师套装",
    "Tier 10 Warlock": "T10术士套装",
    "Tier 10 Death Knight": "T10死亡骑士套装",
    "Tier 10 Druid": "T10德鲁伊套装",
    # ===== 品质描述 =====
    "common": "普通",
    "uncommon": "优秀",
    "rare": "精良",
    "epic": "史诗",
    "legendary": "传说",
}

def get_chinese_name(english_name: str) -> str:
    """获取中文名称，如果没有映射则返回原名称"""
    return chinese_item_names.get(english_name, english_name)
