# 智能装备名称翻译系统

# 常见前缀翻译
prefixes = {
    "Abomination's": "憎恶的",
    "Abomination": "憎恶",
    "Abyssal": "深渊",
    "Accursed": "被诅咒的",
    "Adamant": "坚硬的",
    "Adamantine": "精钢",
    "Adorned": "装饰的",
    "Advanced": "高级",
    "Aegis": "庇护",
    "Aeonus's": "永恒的",
    "Aesir's": "艾西尔的",
    "Agamaggan's": "阿迦玛甘的",
    "Aged": "陈旧的",
    "Agonal": "痛苦的",
    "Ahn'kahar": "安卡哈",
    "Akil'zon's": "阿克希尔宗的",
    "Alabaster": "雪花石膏",
    "Alanna's": "阿兰娜的",
    "Albino": "白化",
    "Alchemist's": "炼金师的",
    "Aldori": "奥尔多",
    "Aldriana's": "奥德里亚娜的",
    "Ancient": "远古的",
    "Andorhal": "安多哈尔",
    "Angerforge": "怒火熔炉",
    "Annhylde's": "安海尔德的",
    "Apocalypse": "天启",
    "Arcanist's": "奥术师的",
    "Arch": "大",
    "Arctic": "北极",
    "Argent": "银色",
    "Armored": "装甲的",
    "Armsmaster's": "武器大师的",
    "Ash": "灰烬",
    "Ashen": "灰烬的",
    "Assassin's": "刺客的",
    "Astral": "星界",
    "Auchenai": "奥金奈",
    "Azeroth": "艾泽拉斯",
    "Azure": "蔚蓝",
    "Baelgun's": "贝尔贡的",
    "Bane": "灾",
    "Barbed": "带刺的",
    "Baron's": "男爵的",
    "Battle": "战斗",
    "Battlemaster's": "战斗大师的",
    "Beast": "野兽",
    "Beastmaster's": "兽王的",
    "Belgorok's": "贝尔戈洛克的",
    "Berserker": "狂战士",
    "Bile": "胆汁",
    "Black": "黑色",
    "Blackened": "熏黑的",
    "Blade": "刃",
    "Blood": "血",
    "Bloodsoaked": "血染的",
    "Bloodthirsty": "嗜血的",
    "Blue": "蓝色",
    "Bluespore": "蓝孢",
    "Bone": "骨",
    "Bonechewer": "嚼骨",
    "Bonereaver": "裂骨者",
    "Boots": "之靴",
    "Bracer": "护腕",
    "Bracelet": "手镯",
    "Brambleskin": "荆棘皮",
    "Breastplate": "胸甲",
    "Brilliant": "璀璨的",
    "Brutal": "残酷的",
    "Buckle": "带扣",
    "Bulwark": "壁垒",
    "Burlap": "粗麻布",
    "Burning": "燃烧的",
    "Cabalist's": "秘法师的",
    "Cage": "牢笼",
    "Cairne's": "凯恩的",
    "Carnage": "屠杀",
    "Carapace": "甲壳",
    "Cloak": "斗篷",
    "Cobalt": "钴蓝",
    "Cold": "寒冷",
    "Coldsteel": "冷钢",
    "Colossus": "巨人",
    "Combat": "战斗",
    "Commander's": "指挥官的",
    "Conqueror's": "征服者的",
    "Corrupted": "腐化的",
    "Crimson": "深红",
    "Crown": "王冠",
    "Cruel": "残酷",
    "Crusader": "十字军",
    "Crypt": "墓穴",
    "Crystal": "水晶",
    "Dagger": "匕首",
    "Dark": "黑暗",
    "Darkened": "黑暗的",
    "Darkruned": "暗纹",
    "Death": "死亡",
    "Deathdealer's": "死亡使者的",
    "Death's": "死亡的",
    "Defender": "防御者",
    "Demon": "恶魔",
    "Demonstalker": "追猎恶魔者",
    "Desecrated": "被亵渎的",
    "Destruction": "毁灭",
    "Devout": "虔诚的",
    "Dire": "恐怖",
    "Dread": "恐惧",
    "Dreadnought": "无畏",
    "Dragon": "龙",
    "Dragonbone": "龙骨",
    "Dragonhide": "龙鳞",
    "Dragonscale": "龙鳞",
    "Dreadnaught": "无畏",
    "Dwarven": "矮人",
    "Earthen": "大地",
    "Ebon": "玄铁",
    "Eclipse": "蚀",
    "Ember": "余烬",
    "Emberlight": "烬光",
    "Eternal": "永恒",
    "Everlasting": "永恒的",
    "Eye": "眼",
    "Fel": "邪能",
    "Feral": "野性",
    "Fierce": "凶猛的",
    "Fire": "火",
    "Firesoul": "火魂",
    "Flame": "火焰",
    "Flamewaker": "烈焰行者",
    "Flesh": "血肉",
    "Floating": "漂浮",
    "Frost": "冰霜",
    "Frostfire": "霜火",
    "Frostforged": "霜铸",
    "Frostscale": "霜鳞",
    "Froststeel": "霜钢",
    "Frozen": "冻结的",
    "Gauntlets": "护手",
    "Ghost": "幽灵",
    "Giant": "巨人",
    "Gilded": "镀金的",
    "Gladiator's": "角斗士的",
    "Gloves": "手套",
    "Gloom": "幽暗",
    "Gnome": "侏儒",
    "Golden": "金色",
    "Gore": "血",
    "Gorefiend's": "血魔的",
    "Grand": "宏伟的",
    "Great": "伟大的",
    "Grievous": "痛苦的",
    "Guardian": "守护者",
    "Guile": "狡诈",
    "Guild": "公会",
    "Hailstone": "冰雹",
    "Hakkar's": "哈卡的",
    "Hallow's": "神圣的",
    "Harbringer": "先驱",
    "Hardened": "硬化的",
    "Hate": "憎恨",
    "Haunted": "闹鬼的",
    "Heart": "之心",
    "Helm": "头盔",
    "Hellfire": "地狱火",
    "Heroic": "英雄",
    "High": "高级",
    "Hood": "兜帽",
    "Horror": "恐惧",
    "Ice": "冰",
    "Icy": "冰冷的",
    "Imbued": "灌输的",
    "Infinite": "无限",
    "Iron": "铁",
    "Ironspine": "铁脊",
    "Ivory": "象牙",
    "Jade": "碧玉",
    "Juggernaut": "主宰",
    "Kael'thas's": "凯尔萨斯的",
    "Kaleidoscope": "万花筒",
    "King's": "国王的",
    "Kirin Tor": "肯瑞托",
    "Knight's": "骑士的",
    "Korgath's": "寇加尔的",
    "Kromcrush": "克罗姆碎",
    "Lance": "长枪",
    "Leggings": "护腿",
    "Legplates": "腿甲",
    "Light": "光",
    "Lightsworn": "圣光使者",
    "Lionheart": "狮心",
    "Living": "活的",
    "Loam": "沃土",
    "Lord's": "领主的",
    "Lunar": "月",
    "Malicious": "恶毒的",
    "Malevolent": "恶意的",
    "Mammoth": "猛犸",
    "Mantle": "披风",
    "Mark": "印记",
    "Master's": "大师的",
    "Maw": "喉",
    "Merciless": "无情的",
    "Midnight": "午夜",
    "Mighty": "强大的",
    "Mithril": "秘银",
    "Moon": "月",
    "Moonshroud": "月影",
    "Mortal": "凡人",
    "Moss": "苔藓",
    "Naga": "纳迦",
    "Nathrezim": "纳斯雷兹姆",
    "Naxxramas": "纳克萨玛斯",
    "Necklace": "项链",
    "Necro": "死灵",
    "Necropolis": "大墓地",
    "Night": "夜",
    "Nightmare": "梦魇",
    "Noble": "高贵的",
    "Obsidian": "黑曜石",
    "Onyx": "缟玛瑙",
    "Oracle's": "神谕者的",
    "Overlord's": "霸主的",
    "Padded": "填充的",
    "Pain": "痛苦",
    "Pale": "苍白",
    "Pendant": "吊坠",
    "Phantom": "幻影",
    "Plague": "瘟疫",
    "Plated": "板甲的",
    "Plate": "板甲",
    "Poison": "毒药",
    "Polished": "抛光的",
    "Primal": "原始",
    "Primordial": "原初",
    "Protector": "守护者",
    "Proudmoore": "普罗德摩尔",
    "Purified": "净化的",
    "Raven": "渡鸦",
    "Razor": "剃刀",
    "Reaper": "收割者",
    "Red": "红色",
    "Relentless": "无情的",
    "Reliquary": "圣物匣",
    "Rend": "撕裂",
    "Rift": "裂隙",
    "Ritualist's": "仪式师的",
    "Robe": "长袍",
    "Runic": "符文",
    "Runed": "符文的",
    "Saber": "军刀",
    "Sage": "贤者",
    "Sanctified": "神圣的",
    "Sapphire": "蓝宝石",
    "Saronite": "萨隆邪铁",
    "Satchel": "背包",
    "Savage": "野蛮的",
    "Scale": "鳞片",
    "Scaled": "鳞甲的",
    "Scarlet": "猩红",
    "Scourge": "天灾",
    "Scourgeborne": "天灾",
    "Shadow": "暗影",
    "Shadowscale": "暗影鳞片",
    "Shadowsong": "暗影之歌",
    "Shard": "碎片",
    "Shield": "盾牌",
    "Shimmering": "闪烁的",
    "Shining": "闪亮的",
    "Silent": "沉默的",
    "Silver": "银色",
    "Skull": "骷髅",
    "Skulking": "潜行的",
    "Slayer": "杀手",
    "Slick": "光滑的",
    "Skeleton": "骷髅",
    "Skull": "骷髅",
    "Snow": "雪",
    "Soul": "灵魂",
    "Soulflayer": "灵魂剥离者",
    "Spiked": "带刺的",
    "Spirit": "精神",
    "Spiteful": "恶意的",
    "Splintered": "破碎的",
    "Spore": "孢子",
    "Storm": "风暴",
    "Stormcaller": "风暴召唤者",
    "Stormscale": "风暴鳞",
    "Sundering": "裂",
    "Sun": "太阳",
    "Sunwell": "太阳之井",
    "Swift": "迅捷",
    "Tactical": "战术",
    "Talon": "利爪",
    "Tankard": "酒杯",
    "Tattered": "破烂的",
    "Tectonic": "构造",
    "Tempered": "回火的",
    "Tender": "脆弱的",
    "Thunder": "雷霆",
    "Thunderhead": "雷霆之头",
    "Titan": "泰坦",
    "Titansteel": "泰坦精钢",
    "Torch": "火炬",
    "Tormented": "痛苦的",
    "Triumphant": "凯旋",
    "Twilight": "暮光",
    "Unbroken": "不破的",
    "Uncanny": "离奇的",
    "Undead": "亡灵",
    "Unholy": "邪恶",
    "Vambrace": "护腕",
    "Vanguard": "先锋",
    "Vengeful": "复仇的",
    "Venom": "毒液",
    "Verdant": "翠绿的",
    "Vestments": "法衣",
    "Vicious": "恶毒的",
    "Void": "虚空",
    "Voidheart": "虚空之心",
    "Voidscale": "虚空鳞片",
    "Volcanic": "火山的",
    "Wand": "魔杖",
    "War": "战争",
    "Warden": "典狱长",
    "Warlock": "术士",
    "Warlord": "军阀",
    "Warrior": "战士",
    "Warmage": "战斗法师",
    "Wartorn": "饱受战争的",
    "Watchman's": "守望者的",
    "Wayward": "迷途的",
    "Wicked": "邪恶的",
    "Wild": "狂野",
    "Windsor's": "温莎的",
    "Winter": "冬季",
    "Wisp": "精灵",
    "Witch": "女巫",
    "Wrathful": "狂怒的",
    "Wrath": "愤怒",
    "Wretched": "可怜的",
    "Ymirjar": "约尔姆加德",
    "Zombie": "僵尸",
    "Zul'": "祖尔",
}

# 常见后缀翻译
suffixes = {
    " of the Abyss": "深渊之",
    " of the Ape": "猿猴之",
    " of the Archlich": "巫妖王之",
    " of the Aspect": "守护巨龙之",
    " of the Beast": "野兽之",
    " of the Beastmaster": "兽王之",
    " of the Blood": "鲜血之",
    " of the Champion": "冠军之",
    " of the Colossus": "巨人之",
    " of the Conqueror": "征服者之",
    " of the Corruptor": "腐蚀者之",
    " of the Damned": "被诅咒者之",
    " of the Dead": "死者之",
    " of the Death": "死亡之",
    " of the Demon": "恶魔之",
    " of the Destroyer": "毁灭者之",
    " of the Dragon": "巨龙之",
    " of the Earth": "大地之",
    " of the Elements": "元素之",
    " of the Fallen": "陨落之",
    " of the Frozen": "冰霜之",
    " of the Frost": "霜之",
    " of the Giant": "巨人之",
    " of the Gladiator": "角斗士之",
    " of the Guardian": "守护者之",
    " of the Hunter": "猎手之",
    " of the Ice": "冰之",
    " of the Lich": "巫妖王之",
    " of the Light": "圣光之",
    " of the Lion": "狮子之",
    " of the Lord": "领主之",
    " of the Mage": "法师之",
    " of the Moon": "月之",
    " of the Mountain": "山之",
    " of the Night": "夜之",
    " of the Plague": "瘟疫之",
    " of the Protector": "守护者之",
    " of the Raven": "渡鸦之",
    " of the Reaper": "收割者之",
    " of the Scourge": "天灾之",
    " of the Shadow": "暗影之",
    " of the Shaman": "萨满之",
    " of the Silver Hand": "白银之手之",
    " of the Soul": "灵魂之",
    " of the Storm": "风暴之",
    " of the Sun": "太阳之",
    " of the Titans": "泰坦之",
    " of the Undead": "亡灵之",
    " of the Unholy": "邪恶之",
    " of the Vanquisher": "胜利者之",
    " of the Void": "虚空之",
    " of the Warlock": "术士之",
    " of the Warrior": "战士之",
    " of Winter": "寒冬之",
    " of Wrath": "愤怒之",
    
    "'s Blood": "之血",
    "'s Bite": "之咬",
    "'s Breath": "之息",
    "'s Claw": "之爪",
    "'s Cudgel": "之棒",
    "'s Edge": "之刃",
    "'s Eye": "之眼",
    "'s Fury": "之怒",
    "'s Grace": "之恩典",
    "'s Grip": "之握",
    "'s Hammer": "之锤",
    "'s Might": "之力",
    "'s Protection": "之庇护",
    "'s Reach": "之触",
    "'s Shadow": "之影",
    "'s Song": "之歌",
    "'s Tears": "之泪",
    "'s Touch": "之触",
    "'s Will": "之意志",
    "'s Wrath": "之怒",
    
    " Armor": "护甲",
    " Band": "束带",
    " Belt": "腰带",
    " Bracers": "护腕",
    " Cape": "披风",
    " Chain": "项链",
    " Cloak": "斗篷",
    " Cover": "护罩",
    " Crown": "王冠",
    " Dagger": "匕首",
    " Gauntlets": "护手",
    " Gloves": "手套",
    " Greatsword": "巨剑",
    " Greaves": "护胫",
    " Hammer": "锤",
    " Handguards": "护手",
    " Helm": "头盔",
    " Idol": "神像",
    " Knife": "刀",
    " Leggings": "护腿",
    " Legplates": "腿甲",
    " Mace": "锤",
    " Necklace": "项链",
    " Pauldrons": "肩甲",
    " Ring": "戒指",
    " Robe": "长袍",
    " Sash": "腰带",
    " Shield": "盾牌",
    " Shoulders": "肩甲",
    " Shoulderpads": "肩垫",
    " Spaulders": "肩甲",
    " Staff": "法杖",
    " Sword": "剑",
    " Treads": "战靴",
    " Wand": "魔杖",
    " Wraps": "裹手",
}

# 常见单词翻译
words = {
    "Abomination": "憎恶",
    "Abyss": "深渊",
    "Armor": "护甲",
    "Band": "束带",
    "Belt": "腰带",
    "Bite": "咬",
    "Blade": "刃",
    "Blood": "血",
    "Boots": "靴子",
    "Bracer": "护腕",
    "Breastplate": "胸甲",
    "Cape": "披风",
    "Cloak": "斗篷",
    "Crown": "王冠",
    "Dagger": "匕首",
    "Edge": "刃",
    "Eye": "眼",
    "Fury": "怒",
    "Gauntlets": "护手",
    "Gloves": "手套",
    "Greatsword": "巨剑",
    "Greaves": "护胫",
    "Hammer": "锤",
    "Handguards": "护手",
    "Helm": "头盔",
    "Idol": "神像",
    "Leggings": "护腿",
    "Legplates": "腿甲",
    "Mace": "锤",
    "Necklace": "项链",
    "Pauldrons": "肩甲",
    "Reach": "触",
    "Ring": "戒指",
    "Robe": "长袍",
    "Sash": "腰带",
    "Shield": "盾牌",
    "Shoulders": "肩甲",
    "Shoulderpads": "肩垫",
    "Spaulders": "肩甲",
    "Staff": "法杖",
    "Sword": "剑",
    "Treads": "战靴",
    "Wand": "魔杖",
    "Wraps": "裹手",
}

def translate_item_name(english_name: str) -> str:
    """智能翻译装备名称"""
    result = english_name
    
    # 优先处理后缀（从长到短）
    for suffix in sorted(suffixes.keys(), key=lambda x: -len(x)):
        if result.endswith(suffix):
            result = result[:-len(suffix)] + suffixes[suffix]
            break
    
    # 处理前缀（从长到短）
    for prefix in sorted(prefixes.keys(), key=lambda x: -len(x)):
        if result.startswith(prefix):
            result = prefixes[prefix] + result[len(prefix):]
            break
    
    # 处理中间单词
    for word in words.keys():
        if word in result and not (result.startswith(word) or result.endswith(word)):
            result = result.replace(word, words[word])
    
    # 特殊处理：移除多余的空格
    result = result.replace("  ", " ").strip()
    
    return result

# 测试翻译
if __name__ == "__main__":
    test_items = [
        "Abomination Knuckles",
        "Abomination Shoulderblades",
        "Abyssal Rune",
        "Ace of Beasts",
        "Acid Inscribed Pauldrons",
        "Aegis of the Coliseum",
        "Aesir's Edge",
        "Agamaggan's Clutch",
        "Alabaster Idol",
        "Aldori Legacy Defender",
    ]
    
    print("测试翻译结果：")
    for item in test_items:
        print(f"{item} -> {translate_item_name(item)}")
